import { jsPDF } from 'jspdf';
import type { ApexCertificateTemplate } from '../types';

function getString(value: unknown, fallback: string): string {
  if (typeof value === 'string' && value.trim()) return value;
  return fallback;
}

export async function buildApexCertificatePdfDocument(opts: {
  template: ApexCertificateTemplate;
  learnerName?: string;
  courseTitle?: string;
  fr: boolean;
}): Promise<jsPDF> {
  const { template, learnerName, courseTitle, fr } = opts;
  const body = template.body || {};

  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const margin = 64;
  let y = margin;

  const title = getString(
    (body as any).title,
    fr ? 'Certificat de complétion' : 'Certificate of completion',
  );

  const issuer = getString(
    (body as any).issuer,
    fr ? 'COYA — APEX' : 'COYA — APEX',
  );

  const legalMention = getString(
    (body as any).legalMention,
    fr
      ? "Document indicatif généré par COYA APEX — la signature manuelle ou une procédure interne peut rester requise."
      : 'Indicative document generated by COYA APEX — manual signature or an internal procedure may still be required.',
  );

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.text(title, margin, y);
  y += 40;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(12);

  if (learnerName) {
    const line = fr
      ? `Délivré à : ${learnerName}`
      : `Issued to: ${learnerName}`;
    doc.text(line, margin, y);
    y += 22;
  }

  if (courseTitle) {
    const line = fr
      ? `Pour le parcours : ${courseTitle}`
      : `For the course: ${courseTitle}`;
    doc.text(line, margin, y);
    y += 22;
  }

  doc.text(
    fr
      ? `Émis par : ${issuer}`
      : `Issued by: ${issuer}`,
    margin,
    y,
  );
  y += 32;

  doc.setFontSize(10);
  const legalLines = doc.splitTextToSize(legalMention, 460);
  doc.text(legalLines, margin, y);

  return doc;
}

export async function downloadApexCertificatePdf(opts: Parameters<typeof buildApexCertificatePdfDocument>[0]): Promise<void> {
  const doc = await buildApexCertificatePdfDocument(opts);
  const safeName = (opts.learnerName || 'participant').replace(/[^\w\-]+/g, '_').slice(0, 40);
  const base = opts.fr ? 'attestation' : 'certificate';
  doc.save(`${base}_${safeName || 'apex'}.pdf`);
}

